import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
        <nav className="w-full bg-blue-700 text-white py-4 px-6 flex items-center justify-between shadow-md mb-8">
          <div className="font-bold text-xl tracking-wide">
            <Link href="/">MINICORE</Link>
          </div>
          <div className="flex gap-6 text-base">
            <Link href="/vendedores" className="hover:underline">Vendedores</Link>
            <Link href="/reglas" className="hover:underline">Reglas</Link>
            <Link href="/ventas" className="hover:underline">Ventas</Link>
            <Link href="/comisiones" className="hover:underline">Comisiones</Link>
          </div>
        </nav>
        <main className="w-full max-w-3xl mx-auto px-4">{children}</main>
      </body>
    </html>
  );
}
